### ISSUE TITLE
Сделать возможность "человеческого" ввода адреса, без формата URL.

### ISSUE THREAD

**Issue by snakeduse** [Oshi41/TFSService#6]
При подключении, вместо строки "https://la-la-la/tfs/Endpoint%20Security", должна быть возможность указать строку "https://la-la-la/tfs/Endpoint Security"

**Comment by Oshi41** [comment]
Мы строку передаем в URL, она уже сама экранирует символы.
Предварительно это и так можно, но лучше протестировать

**Comment by snakeduse** [comment]
Когда я передавал строку без экранированных символов(%20), приложение писало, что адрес был не валидным.

**Comment by Oshi41** [comment]
Насколько я помню, была передана строка "https://la-la-la/Endpoint Security" без "/tfs".
Поэтому и отламывалось.
Проверено, URL экранирует символы на автомате
